all:
	make -C Top_content_categories_of_sites
	make -C Top_TLDs
	make -C Top_SW_Ad_Servers

clean:
	make clean -C Top_content_categories_of_sites
	make clean -C Top_TLDs
	make clean -C Top_SW_Ad_Servers
