all:
	make -C Top_content_categories_of_sites
	make -C Top_TLDs
	make -C Top_SW_Ad_Servers
	make -C Number_of_Ad_servers_plot
	make -C Number_of_3rd_party_servers_plot
	make -C Rank
	make -C	Top_content_ads
	make -C Ad_servers

clean:
	make clean -C Top_content_categories_of_sites
	make clean -C Top_TLDs
	make clean -C Number_of_Ad_servers_plot
	make clean -C Top_SW_Ad_Servers
	make clean -C Number_of_3rd_party_servers_plot
	make clean -C Rank
	make clean -C Top_content_ads
	make clean -C Ad_servers